// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	PersonNo             int64    `protobuf:"varint,1,opt,name=person_no,json=personNo,proto3" json:"person_no,omitempty"`
	PersonId             string   `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName           string   `protobuf:"bytes,3,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	PersonPosition       string   `protobuf:"bytes,4,opt,name=person_position,json=personPosition,proto3" json:"person_position,omitempty"`
	PersonMail           string   `protobuf:"bytes,5,opt,name=person_mail,json=personMail,proto3" json:"person_mail,omitempty"`
	PersonTelephone      string   `protobuf:"bytes,6,opt,name=person_telephone,json=personTelephone,proto3" json:"person_telephone,omitempty"`
	PersonPassword       string   `protobuf:"bytes,7,opt,name=person_password,json=personPassword,proto3" json:"person_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetPersonNo() int64 {
	if m != nil {
		return m.PersonNo
	}
	return 0
}

func (m *Person) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

func (m *Person) GetPersonName() string {
	if m != nil {
		return m.PersonName
	}
	return ""
}

func (m *Person) GetPersonPosition() string {
	if m != nil {
		return m.PersonPosition
	}
	return ""
}

func (m *Person) GetPersonMail() string {
	if m != nil {
		return m.PersonMail
	}
	return ""
}

func (m *Person) GetPersonTelephone() string {
	if m != nil {
		return m.PersonTelephone
	}
	return ""
}

func (m *Person) GetPersonPassword() string {
	if m != nil {
		return m.PersonPassword
	}
	return ""
}

type PersonNo struct {
	PersonNo             int64    `protobuf:"varint,1,opt,name=person_no,json=personNo,proto3" json:"person_no,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonNo) Reset()         { *m = PersonNo{} }
func (m *PersonNo) String() string { return proto.CompactTextString(m) }
func (*PersonNo) ProtoMessage()    {}
func (*PersonNo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *PersonNo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonNo.Unmarshal(m, b)
}
func (m *PersonNo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonNo.Marshal(b, m, deterministic)
}
func (m *PersonNo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonNo.Merge(m, src)
}
func (m *PersonNo) XXX_Size() int {
	return xxx_messageInfo_PersonNo.Size(m)
}
func (m *PersonNo) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonNo.DiscardUnknown(m)
}

var xxx_messageInfo_PersonNo proto.InternalMessageInfo

func (m *PersonNo) GetPersonNo() int64 {
	if m != nil {
		return m.PersonNo
	}
	return 0
}

type PersonID struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonID) Reset()         { *m = PersonID{} }
func (m *PersonID) String() string { return proto.CompactTextString(m) }
func (*PersonID) ProtoMessage()    {}
func (*PersonID) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *PersonID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonID.Unmarshal(m, b)
}
func (m *PersonID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonID.Marshal(b, m, deterministic)
}
func (m *PersonID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonID.Merge(m, src)
}
func (m *PersonID) XXX_Size() int {
	return xxx_messageInfo_PersonID.Size(m)
}
func (m *PersonID) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonID.DiscardUnknown(m)
}

var xxx_messageInfo_PersonID proto.InternalMessageInfo

func (m *PersonID) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

type PersonList struct {
	List                 []*Person `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PersonList) Reset()         { *m = PersonList{} }
func (m *PersonList) String() string { return proto.CompactTextString(m) }
func (*PersonList) ProtoMessage()    {}
func (*PersonList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *PersonList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonList.Unmarshal(m, b)
}
func (m *PersonList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonList.Marshal(b, m, deterministic)
}
func (m *PersonList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonList.Merge(m, src)
}
func (m *PersonList) XXX_Size() int {
	return xxx_messageInfo_PersonList.Size(m)
}
func (m *PersonList) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonList.DiscardUnknown(m)
}

var xxx_messageInfo_PersonList proto.InternalMessageInfo

func (m *PersonList) GetList() []*Person {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*PersonNo)(nil), "PersonNo")
	proto.RegisterType((*PersonID)(nil), "PersonID")
	proto.RegisterType((*PersonList)(nil), "PersonList")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x4f, 0x6b, 0x83, 0x40,
	0x10, 0xc5, 0x6b, 0x4c, 0x35, 0x4e, 0xe8, 0x1f, 0xf6, 0xb4, 0xc4, 0x43, 0x45, 0x28, 0x31, 0x17,
	0x53, 0xd2, 0x6f, 0x50, 0x02, 0x45, 0x68, 0x8b, 0x84, 0xde, 0x8b, 0xc1, 0x69, 0xba, 0xa0, 0x8e,
	0xb8, 0x1b, 0x4a, 0x8e, 0xfd, 0xe6, 0x85, 0xdd, 0x95, 0x28, 0xb9, 0x39, 0xef, 0xfd, 0x66, 0x1e,
	0xbe, 0x05, 0x38, 0x4a, 0xec, 0xd2, 0xb6, 0x23, 0x45, 0x8b, 0xf0, 0x40, 0x74, 0xa8, 0x70, 0xad,
	0xa7, 0xfd, 0xf1, 0x7b, 0x8d, 0x75, 0xab, 0x4e, 0xc6, 0x8c, 0xff, 0x26, 0xe0, 0xe5, 0xd8, 0x49,
	0x6a, 0x58, 0x08, 0x41, 0xab, 0xbf, 0xbe, 0x1a, 0xe2, 0x4e, 0xe4, 0x24, 0xee, 0x6e, 0x66, 0x84,
	0x0f, 0x1a, 0x98, 0xa2, 0xe4, 0x93, 0xc8, 0x49, 0x82, 0xde, 0xcc, 0x4a, 0xf6, 0x00, 0xf3, 0x7e,
	0xb3, 0xa8, 0x91, 0xbb, 0xda, 0x06, 0xbb, 0x5b, 0xd4, 0xc8, 0x96, 0x70, 0x67, 0x81, 0x96, 0xa4,
	0x50, 0x82, 0x1a, 0x3e, 0xd5, 0xd0, 0xad, 0x91, 0x73, 0xab, 0x0e, 0x2e, 0xd5, 0x85, 0xa8, 0xf8,
	0xf5, 0xf0, 0xd2, 0x7b, 0x21, 0x2a, 0xb6, 0x82, 0x7b, 0x0b, 0x28, 0xac, 0xb0, 0xfd, 0xa1, 0x06,
	0xb9, 0xa7, 0x29, 0x9b, 0xf0, 0xd9, 0xcb, 0xc3, 0xd0, 0x42, 0xca, 0x5f, 0xea, 0x4a, 0xee, 0x8f,
	0x42, 0xad, 0x1a, 0x2f, 0x61, 0x96, 0x5f, 0xfe, 0xe7, 0x65, 0x09, 0x67, 0x30, 0xdb, 0x8e, 0x0b,
	0x71, 0xc6, 0x85, 0xc4, 0x2b, 0x00, 0x03, 0xbe, 0x09, 0xa9, 0x58, 0x08, 0xd3, 0x4a, 0x48, 0xc5,
	0x9d, 0xc8, 0x4d, 0xe6, 0x1b, 0x3f, 0x35, 0xd6, 0x4e, 0x8b, 0x9b, 0x27, 0xf0, 0xcd, 0x2c, 0xd9,
	0x23, 0xdc, 0xbc, 0xa2, 0x32, 0xd3, 0xcb, 0x29, 0xdb, 0xb2, 0x20, 0xed, 0xe3, 0x16, 0xfd, 0x56,
	0x7c, 0xb5, 0xf7, 0xf4, 0xcb, 0x3d, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x27, 0x80, 0x9f, 0x1e,
	0xe4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonsClient is the client API for Persons service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonsClient interface {
	GetPersonByID(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*Person, error)
}

type personsClient struct {
	cc *grpc.ClientConn
}

func NewPersonsClient(cc *grpc.ClientConn) PersonsClient {
	return &personsClient{cc}
}

func (c *personsClient) GetPersonByID(ctx context.Context, in *PersonID, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/Persons/GetPersonByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonsServer is the server API for Persons service.
type PersonsServer interface {
	GetPersonByID(context.Context, *PersonID) (*Person, error)
}

// UnimplementedPersonsServer can be embedded to have forward compatible implementations.
type UnimplementedPersonsServer struct {
}

func (*UnimplementedPersonsServer) GetPersonByID(ctx context.Context, req *PersonID) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonByID not implemented")
}

func RegisterPersonsServer(s *grpc.Server, srv PersonsServer) {
	s.RegisterService(&_Persons_serviceDesc, srv)
}

func _Persons_GetPersonByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonsServer).GetPersonByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Persons/GetPersonByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonsServer).GetPersonByID(ctx, req.(*PersonID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Persons_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Persons",
	HandlerType: (*PersonsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonByID",
			Handler:    _Persons_GetPersonByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
